#! /usr/bin/env python

"""
Format the csv files to have the desired format

"""

__author__= "Cameron Durie"

import csv

define formating(folder = None)

    if folder = None
        folder = './Data_set_2_small'

    filenames = glob.glob(folder + "/*.csv")

    with open(folder)